import IProduct from './IProduct';

export default interface State {
  cart: IProduct[];
  products: IProduct[];
}

export const initialState: State = {
  cart: [],
  products: [
    {
      title: 'Camiseta Spider Venom',
      description: 'Camiseta azul unisex Spiderman y Venom reflectiva',
      id: '1',
      image: 'https://i.imgur.com/CqHKJqU.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 45000.5,
    },
    {
      title: 'Camiseta Batman mujer',
      description: 'Camiseta negra logo batman para mujer',
      id: '4',
      image: 'https://i.imgur.com/VchqPwf.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 41000,
    },
    {
      title: 'Mug flash',
      description: 'Mug cara de flash, cambio de color con la temperatura',
      id: '5',
      image: 'https://i.imgur.com/RZSX68z.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 48900,
    },
    {
      title: 'Camiseta mujer maravilla',
      description: 'Camiseta mujer maravilla blanca',
      id: '6',
      image: 'https://i.imgur.com/gyKyjf0.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 34500,
    },
    {
      title: 'Funko thanos',
      description:
        'Figura animada funko, thanos activando las gemas del infinito',
      id: '7',
      image: 'https://i.imgur.com/yPp5yhm.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 142000,
    },
    {
      title: 'Buzo pink floyd retro',
      description: 'Buzo Pink floy - dark side of the moon retro',
      id: '2',
      image: 'https://i.imgur.com/aHWXP8j.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 89999,
    },
    {
      title: 'Mug game of thrones',
      description: 'Mug game of thrones con logo familia stark',
      id: '8',
      image: 'https://i.imgur.com/vmS25of.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 44500,
    },
    {
      title: 'Camiseta Venom',
      description: 'Camiseta gris hombre Venom reflectiva',
      id: '9',
      image: 'https://i.imgur.com/JXJd8ld.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 44900,
    },
    {
      title: 'Funko Bruja Escarlata',
      description: 'Figura animada funko, Wanda Maximoff - bruja escarlata',
      id: '10',
      image: 'https://i.imgur.com/TJTsuQf.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 190000,
    },
    {
      title: 'Buzo deadpool',
      description: 'Buzo deadpool rojo unisex',
      id: '11',
      image: 'https://i.imgur.com/Myhu6XN.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 94000,
    },
    {
      title: 'Martillo Thor',
      description: 'Martillo Thor Mjölnir escala 1:1',
      id: '12',
      image: 'https://i.imgur.com/TfNaFt4.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 310000,
    },
    {
      title: 'Camiseta Spiderman',
      description: 'Camiseta roja hombre Spiderman',
      id: '13',
      image: 'https://i.imgur.com/tm4rbXE.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 41500,
    },
    {
      title: 'Funko Deadpool',
      description: 'Figura animada funko, Deadpool bailador de tango',
      id: '14',
      image: 'https://i.imgur.com/O0TlkEp.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 131900,
    },
    {
      title: 'Funko Baby Yoda',
      description: 'Figura animada funko, Baby Yoda - The Child saga star wars',
      id: '15',
      image: 'https://i.imgur.com/j7NM3wB.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 180000,
    },
    {
      title: 'Buzo marvel',
      description: 'Buzo unisex logo de marvel',
      id: '3',
      image: 'https://i.imgur.com/TYyomRh.png',
      inCart: false,
      count: 1,
      total: 12,
      price: 98000,
    },
  ],
};
